@startuml
'https://plantuml.com/component-diagram

node "lsh"{
	[Kernel] <--> [UI] : Interact with users.
	[Kernel] -> [Parser] : Parse commands script.
	[Parser] --> [Kernel] : Return parse result.
	[EnvVar] <--> [Kernel] : Support.
	[Kernel] -> [Runner] : Give commands to run.
	[Runner] --> [Kernel] : Return result.
	[Kernel] <--> [History] : Load/Restore history command.
}
node "User"{
	User --> [UI] : Input Command.
	[UI] --> User : Print Result and information.
}
node "OS" {
	folder BinPath
	[Kernel] -> BinPath : Find executable.
}






@enduml